### ISSUE TITLE
Add hmat-oss to the list of C++ libraries

### ISSUE THREAD

**Issue by regislebrun** [gchavez2/awesome_hierarchical_matrices#8]
Hi,

Many thanks for this list!

Are you aware of the hmat-oss library? It provides several formats and compression algorithms, and IMO it deserves to should be added to the C++ sectrion.

Cheers

Régis LEBRUN

**Comment by gchavez2** [comment]
Hi there, I was note. Please send me a pull request to add it.

**Comment by gchavez2** [comment]
closing
